config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  resources :categories
  resources :comments
  get 'users/show'
  devise_for :users
  get 'videos/myVideo'

  resources :videos do 
    resources :likes
  end
  
  root to: 'videos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/video.rb
class Video < ApplicationRecord
    is_impressionable #for view count
    has_one_attached :clip
    has_one_attached :thumbnail
    belongs_to :user 
    has_many_attached :comment 
    belongs_to :category

    has_many :likes, dependent: :destroy

    validates :title, presence: true
    validates :description, presence: true
    validate :correct_image_type
    validate :correct_video_type

    # Increment likes counter
    def like!
        self.likes += 1
        save
    end

    private 

    def correct_image_type
        if (thumbnail.attached? && !thumbnail.content_type.in?(%w(image/jpeg image/png)))
            errors.add(:thumbnail, 'must be a JPEG or PNG.')
        elsif thumbnail.attached? ==false
            errors.add(:thumbnail, 'must be attached.')
        end
    end

    def correct_video_type
        if(clip.attached? && !clip.content_type.in?(%w(video/mp4)))
            errors.add(:clip, 'must be MP4.')
            elsif clip.attached? ==false
            errors.add(:clip, 'must be attached.')
        end
    end


end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  impressionist :actions=>[:show,:index]
  # , unique: [:session_hash]

  #check sigin

  # GET view count
  def show
    @videos = Video.find
    impressionist(@videos)
    # impressionist(@videos, "unique view", :unique => [:session_hash])
 end

  # GET /videos or /videos.json
  def index
    @categories = Category.all

    if params[:category].present?
      @videos = Video.where(["category_id IN (?)", Category.where(["category LIKE ?","%#{params[:category]}%"]).pluck(:id)])
    end

    if params[:title].present?
      @videos = Video.where(["title LIKE ?","%#{params[:title]}%"])
    end

    cate = params[:cate]
    if !cate.nil?
      @videos = Video.where(:category_id => cate)
    end
    
    if cate == 'all'
      @videos = Video.all
    end

    if cate.nil? && params[:category].nil? && params[:title].nil?
      @videos = Video.all
    end
  end
  
  #myvideo
  def myVideo 
    # @video = current_user.Videos.all
    @videos = Video.all
   
  end
  

  # GET /videos/1 or /videos/1.json
  def show
    @comment = Comment.new
    @comments = Comment.all
  end

  

  # GET /videos/new 
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    # @user = User.find_by(id: current_user.id)
    
    @video = Video.new(video_params)
    # @video = @user.videos.build(video_params)
    # @video.id = current_user.id
    # @video = Video.new(params[:video])
    @video.user_id = current_user.id

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :category_id, :description, :clip, :thumbnail,:user_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<br/>
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, Category.all.map {|c| [c.category, c.id]} %>
  </div>

  <div class="field">
    <%= form.label :clip%>
    <%= form.file_field :clip%>

    <div class="field">
    <%= form.label :thumbnail%>
    <%= form.file_field :thumbnail%>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>

<div class="row" style="justify-content: center; padding-top: 1.5rem;">
  <div class="col-12 col-xl-3" style="border: 1px solid #cfc3c3;
    font-size: 20px;
    text-align: center;
    text-transform: uppercase;
    border-radius: 8px;
    margin: 0px 0.5rem 1.5rem;"><a href="<%= videos_path(:cate => 'all') %>">All</a></div>
    <% @categories.each do |category| %>
        <div class="col-12 col-xl-3" style="border: 1px solid #cfc3c3;
    font-size: 20px;
    text-align: center;
    text-transform: uppercase;
    border-radius: 8px;
    margin: 0px 0.5rem 1.5rem;"><a href="<%= videos_path(:cate => category.id) %>"><%= category.category %>
        </a></div>
    <% end %>
  
</div>
<%# list category %>
<div class="ms-5 pt-4">
  <p class="fs-3">Filter tool</p>
</div>
<div class="search-flex">

    <%
=begin%>
 <div class "search-flex">
  <%= form_tag videos_path, :method => 'get' do %>
    <%= text_field_tag :category, params[:category], :placeholder => 'Search by category' %>
    <%= submit_tag 'Search by category', class: 'button-control btn btn-outline-dark' %>
  <% end %>
  </div> 
<%
=end%>

  <%# Srearch box%>
  <div class="search-flex ms-5 pt-4">
  <%= form_tag videos_path, :method => 'get' do %>
    <%= text_field_tag :title, params[:title], :placeholder => 'Search by title' %>
    <%= submit_tag 'Search by title', class: 'button-control btn btn-outline-info ms-3' %>
  <% end %>
  </div>

  <!-- Example split danger button -->
<%
=begin%>
 <div class="btn-group">
  <button type="button" class="btn btn-primary">List category</button>
  <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="visually-hidden">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="<%= videos_path(:cate => 'all') %>">All</a></li>
    <li><hr class="dropdown-divider"></li>
    <% @categories.each do |category| %>
      <li>
        <a class="dropdown-item" href="<%= videos_path(:cate => category.id) %>"><%= category.category %>
        </a>
      </li>
    <% end %>
  </ul>
</div> 
<%
=end%>

</div>
<%# Srearch box%>

<div class="ms-5 pt-4">
  <h1>Videos</h1>
</div>

<table id="debug">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <!--
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->

      </tr>
    <% end %>
  </tbody>
</table>

<% if @videos.count == 0%>
  <h1> there are no videos belongs to this category :< !!　申し訳ございません</h1>

<% else %>	
	<%
=begin%>
 <div class="row" id="video-contain">

		<% @videos.each do |video| %>

			<div class="col-md-1 video">
				<a href="/videos/<%= video.id %>">
					<%= image_tag(video.thumbnail, size: "250", data: { title: video.title }) %>
          <br>
          <strong><%= video.title %></strong>
				</a>
        <br>
        <p> category: <%= Category.find(video.category_id.to_i).category %></p>
        <p> duration: <%= ActiveStorage::Analyzer::VideoAnalyzer.new(video.clip.blob).metadata[:duration]%></p> 
        <p> description: <%= video.description %></p>
        <p> <%= video.impressionist_count %> views</p> 

        <p><%= video.likes.count %> <%= (video.likes.count) == 1 ? 'Like' : 'Likes'%></p>
			
      </div>	

		<% end %>

	</div> 
<%
=end%>

  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-12 col-xl-3 px-4" style="text-align: center;">
      <div class="content">
        <a href="/videos/<%= video.id %>">
					<%= image_tag(video.thumbnail, size: "250", data: { title: video.title }, class: 'custom-image')%>
          <br>
          <div class="custom-title"><%= video.title %></div>
				</a>
        <br>
        <p> <%= video.impressionist_count %> views</p> 

        <p><%= video.likes.count %> <%= (video.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      </div>
        <%
=begin%>
 <p> category: <%= Category.find(video.category_id.to_i).category %></p> 
<%
=end%>
        <%
=begin%>
 <p> duration: <%= ActiveStorage::Analyzer::VideoAnalyzer.new(video.clip.blob).metadata[:duration]%></p>  
<%
=end%>
        <%
=begin%>
 <p> description: <%= video.description %></p> 
<%
=end%>
      </div>

		<% end %>
  </div>
<%end%>

<br>
 
<!--<%= link_to 'New Video', new_video_path %>

app/views/videos/myVideo.html.erb
<br/>
<h1>My Videos</h1>

<table>
  <thead>
  <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  <% @videos.each do |video| %>
    
     <% if video.user_id == current_user.id %>
    
  </thead>

  <tbody>
    
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
    


  
	<div class="row">

		<% @videos.each do |video| %>
      <% if video.user_id == current_user.id %>
			<div class="col-md-1">
				<a href="/videos/<%= video.id %>">
					<%= image_tag(video.thumbnail, size: "250", data: { title: video.title }) %>
          <br>
          <strong><%= video.title %></strong>
				</a>
        <br>
        <p> category: <%= Category.find(video.category_id.to_i).category %></p>
        <td> duration: <%= ActiveStorage::Analyzer::VideoAnalyzer.new(video.clip.blob).metadata[:duration]%></td>
        <p> description: <%= video.description %></p>
        <p> <%= video.impressionist_count %> views</p> 
       
			</div>	
    <% end %>

	</div>
<%end%>

<br>
 
<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
 <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />

  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <!-- <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script> -->

<h1>
  <strong>Title:</strong>
  <%= @video.title %>
</h1>

<p class="p-show">
  <strong>Category:</strong>
  <%= @video.category.category %>
</p>
  
<video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="640"
    height="264"
    poster="<%= url_for(@video.thumbnail) %>"
    data-setup="{}"
  >
    <source src="<%= url_for(@video.clip) %>" type="video/mp4" />
    
</video>

<p class="p-show">
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p class="p-show"> <strong>View counts:</strong> <%= @video.impressionist_count %> views</p>


<p　class="p-show">　<strong><%= @video.likes.count %> <%= (@video.likes.count) == 1 ? 'Like' : 'Likes'%></strong></p>

<div class="back-end">
  <%= link_to 'Edit', edit_video_path(@video) %> |
  <%= link_to 'Back', videos_path %>
</div>
<script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script>


<% pre_like = @video.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <a> You liked the video!</a>
  <%= button_to 'Unlike', video_like_path(@video, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', video_likes_path(@video), method: :post %>
<% end %>



<%= form_with(model: @comment) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :video_id %>
    <%= form.hidden_field :video_id, value: @video.id%>
  </div>

  <% if  user_signed_in? %>
    <div class="field">
      <%= form.label :comment, class: "p-show" %>
      <%= form.text_field :comment, class: "form-control" %>
    </div>

    <div class="actions" >
      <%= form.submit  %>
    </div>
  <% end %>
<% end %>

<% @comments.each do |comment| %>
  <% if comment.video_id == @video.id%>
  <div>
    <div>
      <br>
      User: 
      <%= User.find(comment.user_id.to_i).name %>
    </div>
    <strong>
      Comment: 
      <%= comment.comment %>
    </strong>
    <div>
      Time: 
      <%= comment.time %> 
    </div> 
  </div>
  <% end %>
<% end %>